using Documenter, DevOpsMWE

makedocs(
    sitename = "Julia Autogenerated Documentation",
    modules = [DevOpsMWE],
    format = Documenter.HTML(),
    pages = ["index.md"],
    repo = "https://github.com/MolecularTheoryGroup/DevOpsMWE.jl.git",
)

deploydocs(
    repo = "https://github.com/MolecularTheoryGroup/DevOpsMWE.jl.git",
    target = "build",
    branch = "gh-pages",
    devbranch = "main",
    ssh = false,
)