name: Generate Changelog

on:
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install gitchangelog
        run: pip install gitchangelog
      - name: Install pystache
        run: pip install pystache
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run gitchangelog
        run: gitchangelog > CHANGELOG.md
      - name: Create changelog commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md" || true
          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GH_PAT_FULL }}@github.com/${{ github.repository }}.git"
          git push
        env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT_FULL }}

